# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cos_fun <- function(j, k, N) {
    .Call(`_tidynorm_cos_fun`, j, k, N)
}

#' @export
dct_fun <- function(x, kk = 0L, forward = 1L, orth = 1L) {
    .Call(`_tidynorm_dct_fun`, x, kk, forward, orth)
}

idct_fun <- function(y, n) {
    .Call(`_tidynorm_idct_fun`, y, n)
}

idct_prime <- function(y, n) {
    .Call(`_tidynorm_idct_prime`, y, n)
}

idct_dprime <- function(y, n) {
    .Call(`_tidynorm_idct_dprime`, y, n)
}

idct_interp <- function(y, n, p) {
    .Call(`_tidynorm_idct_interp`, y, n, p)
}

