# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cos_fun <- function(j, k, N) {
    .Call(`_tidynorm_cos_fun`, j, k, N)
}

dct_fun <- function(x, kk) {
    .Call(`_tidynorm_dct_fun`, x, kk)
}

idct_fun <- function(y, n) {
    .Call(`_tidynorm_idct_fun`, y, n)
}

idct_prime <- function(y, n) {
    .Call(`_tidynorm_idct_prime`, y, n)
}

idct_dprime <- function(y, n) {
    .Call(`_tidynorm_idct_dprime`, y, n)
}

idct_interp <- function(y, n, p) {
    .Call(`_tidynorm_idct_interp`, y, n, p)
}

